Downlink timing fix
BeelanMX/Beelan-LoRaWAN pull request #58
Opened 2020-10-30 01:53 UTC by wero1414

I modified the lora_cycle to get the standard timing for class C and Class A 

Already tested on Class C, working with a Bug that i wasnt able to catch today, this bug happens when you do the first downlink to the device, once it have received it when the function LORA_Receive_Data() is called, the function RFM_Get_Package() is called inside, and it always return a good CRC, so it gets like if it where a new packet, BUT right now with this example im able to send donwlinks in class C while sending uplinks or when not sending uplinks.

Any help reproducing the bug and also trying to fix it will be really handy!

Do not merge yet, it need more changes! like the support for different regions

2020-10-30 02:04 UTC, wero1414 commented
UPDATE

Class A downlink working stable

2020-10-30 08:53 UTC, mr3188 commented
@wero1414 I'm facing similar bug in my fix, once I send a confirmed downlink then node detect's it but the ackpending flag remains set even if I reset it.

The debug session shows subsequent downlinks are detected but lost somewhere in de code and de bugger jumps from one place to another without sense. I will discard my changes and begin from your branch to see if I can fix it and test it in EU868.

2020-11-02 15:39 UTC, mr3188 commented
@wero1414  don't worry, I was stuck.

2020-11-04 02:16 UTC, wero1414 commented
Just add an example for Serial to LoRaWAN with Class C with ABP

2020-11-23 20:56 UTC, mr3188 commented
@wero1414  Is this ready for merge? Do you still need help with the bug?

I have a branch with some basic  MAC command features including LinkCheck working but it is based on the master. If the work in this branch is finished and just waiting to be merged I can easily modify mine to be based on this. If not, I can try to reproduce the bug and test it with EU_868.

I have started to work on ADR but as much of the work to do is in LoRaMAC.cpp I want to be sure I'm working on the correct branch.

2020-11-25 18:48 UTC, wero1414 commented
Well i havent been able to find a solution for the BUG and also this branch needs the different configurations for different regions, thats all it needs

2020-11-25 19:35 UTC, mr3188 commented
Ok, if you don't mind I will take a look at EU868 changes needed to try to solve the bug.

2020-11-29 10:48 UTC, mr3188 commented
In RF95.cpp LORA_Receive_Data() always set MessageStatus=NEW_MESSAGE if node class is not Class A and then calls RFM_Get_Package() without checking RxDone, then CRC Error interrupt is check but as the Interrupt register returns 0 (no interrupt flagged) it always return CRC_OK and  read 0 bytes from Fifo.
I'm still checking because I can't receive downlinks I always get crc error. I will compare the code with the version I used to create MAX_DONLINK_PAYLOAD_SIZE but may be this information gives you a clue to fix the issue as you know this branch better than me.

2021-01-23 21:17 UTC, sabas1080 requested changes

2021-01-23 21:17 UTC, sabas1080 commented on src/arduino-rfm/LoRaMAC.cpp
> +		pinMode(RFM_SWITCH,OUTPUT);
creo que RFM_Switch debería agregarse a sRFM_pins para que este disponible para cualquier placa

2021-01-23 21:17 UTC, sabas1080 commented on src/arduino-rfm/RFM95.cpp
> +  //LoRa_Settings->Datarate_Rx=10;
Deberian eliminarse estos comentarios?

2021-01-23 21:17 UTC, sabas1080 commented on src/arduino-rfm/RFM95.cpp
> +
Y estos comentarios tambien deberian eliminarse?

2021-01-24 00:41 UTC, ivanmorenoj reviewed
Seems good to me.

2021-07-09 21:33 UTC, wero1414 commented
update timming on Rx for US915

2021-07-09 21:33 UTC, merged